# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano//zmk" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9//zmk
#   - board: nice_nano//zmk
#     shield: reviung41
#
# ---
include:
  # - board: nice_nano//zmk
  #   shield: mov
  - board: xiao_ble//zmk
    shield: charybdis_dongle
    snippet: studio-rpc-usb-uart
  - board: nice_nano//zmk
    shield: charybdis_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: nice_nano//zmk
    shield: charybdis_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  # - board: xiao_ble//zmk
  #   shield: clone_advantage_dongle
  #   snippet: studio-rpc-usb-uart
  - board: nice_nano//zmk
    shield: settings_reset
  - board: xiao_ble//zmk
    shield: settings_reset
#   - board: xiao_ble//zmk
#     shield: settings_reset
# include:
#   - board: xiao_ble//zmk
#     shield: totem_left
#     snippet: studio-rpc-usb-uart
#   - board: xiao_ble//zmk
#     shield: totem_right
#   - board: xiao_ble//zmk
#     shield: settings_reset
