manifest:
  remotes:
    - name: taufiqr
      url-base: https://github.com/taufiqr
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: cosmicbuffalo
      revision: adv360-led
      import: app/west.yml
  self:
    path: config
